services:
  testapi:
    image: mysql:8.0.32
    container_name: test-api
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: +BB=CC1=pNxi
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
